### ISSUE TITLE
[!] super important

### ISSUE THREAD

**Issue by naxitoo** [xafn/afn.lol#30]
Hi, just wanted to say that I loved your website, it feels so warm and welcoming aaaa, the design, the font, the artwork, everything... so cool

Ofc I'm talking about v2, though I must say I really like the artwork in v1 as well

Sorry for posting as issue but there are no discussions

That was it, keep it up :)

**Comment by xafn** [comment]
thank you so much!! your kind words means a lot :)

didn't even think someone would comment on my repo like this so I disabled discussion, guess I'll reenable them
